// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_QGPFGUtHNtekWGm2icTRXa91QBlaoU0',
    appId: '1:114788199709:web:b62f3e32254bfaa4ce45f4',
    messagingSenderId: '114788199709',
    projectId: 'eventlyapp-853e6',
    authDomain: 'eventlyapp-853e6.firebaseapp.com',
    storageBucket: 'eventlyapp-853e6.appspot.com',
    measurementId: 'G-SJY44TE43P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS33MZAlAfcAs1uRcVr8YoI23v_Gfnc1k',
    appId: '1:114788199709:android:0c4e2dd351557448ce45f4',
    messagingSenderId: '114788199709',
    projectId: 'eventlyapp-853e6',
    storageBucket: 'eventlyapp-853e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgNbEPDKBfZzoCJ7JTnzDH57dReb58O_E',
    appId: '1:114788199709:ios:33e04d1dac0edf99ce45f4',
    messagingSenderId: '114788199709',
    projectId: 'eventlyapp-853e6',
    storageBucket: 'eventlyapp-853e6.appspot.com',
    iosClientId: '114788199709-pj402fk9d0hkvkhmsu6ds8k6hntvdk7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.evently',
  );
}
